import type { Timestamp } from "./base";

/**
 * dailyStats/{branchId}_{date}. System-generated by the nightly
 * rollUpDailyStats scheduled function (docs/13-cloud-functions.md §13.2,
 * doc09 §9.7) — a denormalized read cache, not a user-authored record, so it
 * doesn't extend BaseDoc/go through writeWithAudit (nothing to audit: it's
 * an idempotent recomputation of the same day's numbers every run, not a
 * business action). One doc per branch per day; Super Admin's platform view
 * sums across all branches/hospitals for a given date.
 */
export interface DailyStats {
  hospitalId: string;
  branchId: string;
  date: string;
  appointmentsCount: number;
  completedAppointmentsCount: number;
  /** Doctor-utilization denominator (FR-19.2): completedAppointmentsCount / approvedSlotsCount. */
  approvedSlotsCount: number;
  newPatientsCount: number;
  /** Sum of invoices.paidAmount for invoices created that day — a documented simplification, see rollUpDailyStats comment. */
  revenue: number;
  occupiedBedsCount: number;
  totalBedsCount: number;
  updatedAt: Timestamp;
}
